services:
  # Backend FastAPI
  - type: web
    name: attendance-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: 3306
      - key: DATABASE_NAME
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000

databases:
  - name: attendance-db
    databaseName: attendancedb
    user: attendanceuser
    plan: free